version: "3.4"

services:
  trafap:
    image: trafap
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - "./:/app"
  
volumes:
  trafap: