version: "3.4"

services:
  trafap:
    image: trafap
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:8080
    depends_on:
      - database
    volumes:
      - "./:/app"
  
  database:
      image: postgres:14-alpine
      restart: always 
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=trafap
      ports:
        - "5433:5432"
volumes:
  pgdata: